version: "3.8"

services:
  web:
    build: .
    command: bash -c "flask db init && flask db migrate && flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    volumes:
      - .:/code
    ports:
      - 5000:5000
    env_file:
      - ./.flaskenv
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: