"""atualizando

Revision ID: 237d8ced5a4b
Revises: 8e72bb41e378
Create Date: 2021-10-04 22:43:17.738610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237d8ced5a4b'
down_revision = '8e72bb41e378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comment_created_on'), 'comment', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_created_on'), table_name='comment')
    op.drop_column('comment', 'created_on')
    # ### end Alembic commands ###
